model: closenet
device: cuda
debug: True
exp_logs_path: ./closenet_train
optim:
  name: adam
  lr: 5.0e-3
  milestones: []
  gamma: 0.1
  weight_decay: 0.0
data:
  split_file: ./cfg/data_split.json
  data_path: ./data
  n_classes: 18
  pointcloud_samples: 2048
  num_workers: 0
  batch_size: 4
  input: 
    - points
    - colors
    - normals
    - smpl
model_arch:
  garm_enc:
    name: attention_garm
    dropout: 0.0
    emb_dim: 64
    gar_emb_dim: 64
    key_mask: true
    max_norm: 2.0
    n_embeddings: 18
    n_heads: 4
  pc_enc:
    channels_sum: 192
    emb_dim: 1024
    inp_dim: 9
    k: 40
    name: dgcnn
    use_tnet: true
  part_enc:
    name: canon_encoder
  segm_dec:
    channels:
    - 512
    - 512
    - 512
    - 512
    - 256
    dropout: 0.5
    emb_dim: 512
    name: mlp
    segm_input: 1283
    slope: 0.2
training:
  batch_size: 16
  backup_it: -1
  loss_weights:
    segm_loss: 1.0
  max_epochs: 200
  max_iters: -1
  print_it: 200
  selection_metric: mIoU,freq_IoU
  selection_mode: maximize
  val_it: 200
